### ISSUE TITLE
Pivotal Tracker 활용 - 1) contributor 17명을 Tracker 멤버로 초대함

### ISSUE THREAD

**Issue by imyaman** [imyaman/kkeun-ma-rit-gi#35]
# Goal:

Pivotal Tracker를 활용하여 끝말잇기 활동을 계획하고 관리함
# Success:

2016-02-29 기준 contributor 17명을 Tracker의 멤버로 추가
# Related Issues & Links:
#33

Pivotal Tracker의 관련 프로젝트 https://www.pivotaltracker.com/projects/1541149/memberships
# Roles:

Owner: @imyaman
Involved: @svr42mp @imyagirl @iz4blue 
# Required:
- [x] 17명에게 사안을 전파
- [ ] Pivotal Tracker의 설정 메뉴에서 17명을 초대 (@imyaman, large, Due: 2016-03-02)
- [ ] 17명 모두 초대에 응하지 않더라도 초대 메일을 발송하면 이슈는 close

**Comment by imyaman** [comment]
@iz4blue 도와줘 ^^

**Comment by imyaman** [comment]
@yeojoy @iz4blue @iz4blue @imyagirl @haruair @heaven-sweetie @initNirvana @svr42mp @althjs @fra3il @breadval @SoongChoi @luapz @dkmin @socmaster @ParkSangGwon 

Project management를 Pivotal Tracker로 해보려고 합니다. 뭘 재미있게 할진 잘 모르겠지만... 많이 귀찮게는 안 할게요. 놀아주세요. :smile:
본문에 추가된 링크로 가서 멤버로 가입해주시거나, 이메일 주소를 저에게 알려주시면 초대해드릴게요. imyaman@netscape.net

**Comment by breadval** [comment]
@imyaman  가입은했는데.. 어케해야하는지 몰겠네여 ㅋ breadval@hotmail.com

**Comment by imyaman** [comment]
@breadval :+1: 초대 메일 드렸습니다.

**Comment by imyagirl** [comment]
ahsil.chung@gmail.com :smile:

**Comment by imyaman** [comment]
심각한 문제를 발견했습니다. ㅠ_ㅠ 
Free는 collaborator가 3명까지입니다.

**Comment by imyaman** [comment]
@imyagirl 추가했다가 삭제함, 다른 사용자를 한 명 더 얻기 위해.

**Comment by imyaman** [comment]
미안합니다. 제가 실수했습니다. Free로 collaborator 10명인게 있었는데, 그것이랑 햇갈린 것 같습니다. close 하겠습니다.
